export const products=[
{slug:'gang',category:'ORGANIZATIONS',title:'Gang Package',price:'$180',image:'/images/packages/gang.jpg',short:'Build your identity, establish your organization and create your story in the city.',features:['One approved gang territory','One gang chain','One gang outfit package','Official gang recognition','Gang roles and permissions'],delivery:'Estimated setup: 24–48 hours after required information is provided.',terms:['Territory and branding are subject to availability and approval.','Organization status remains subject to city rules and activity standards.','No package guarantees competitive dominance, income or rule exemptions.']},
{slug:'family',category:'ORGANIZATIONS',title:'Family Package',price:'$225',image:'/images/packages/family.jpg',short:'Create a family legacy with approved housing, branding and organization features.',features:['One approved family house','One family chain','One family clothing piece','Official family recognition','Family roles and permissions'],delivery:'Estimated setup: 24–48 hours after required information is provided.',terms:['Housing, branding and content are subject to approval and availability.','Family status remains subject to city rules and activity standards.','No package guarantees competitive dominance, income or rule exemptions.']},
{slug:'business',category:'BUSINESS',title:'Business Package',price:'$280',image:'/images/packages/business.jpg',imageFit:'contain',short:'Own and operate an approved business with defined features and employee management.',features:['One approved business organization','Business setup and management access','Employee recruitment and management','Applicable business features and resources','Staff setup assistance'],delivery:'Estimated setup: 24–48 hours after the business selection is approved.',terms:['Locations, interiors and features depend on availability.','Names, branding and activities are subject to staff approval.','No guaranteed financial outcome, territory, advantage or exemption from city rules.','Business status may be reviewed for inactivity or serious/repeated rule violations.']},
{slug:'mlo',category:'PROPERTY',title:'MLO Package',price:'$250',image:'/images/packages/mlo.jpg',short:'Explore approved property options with clearly listed interiors and included features.',features:['Approved MLO selection','Property setup','Extra storage where included','Eligible elevator setup','Weapon repair bench where listed'],delivery:'Estimated setup: 24–48 hours after an available property is selected.',terms:['Selection is limited to approved, currently available MLOs.','Features vary by the exact property selected and will be listed before fulfillment.','Server updates or balance changes may require feature adjustments.']},
{slug:'drug-plug',category:'CRIMINAL RP',title:'Drug Plug Package',price:'COMING SOON',image:'/images/packages/drug-plug.jpg',short:'A defined criminal-roleplay package built around an approved in-city drug operation.',features:['Approved drug operation concept','Defined product and distribution setup','Roleplay-focused progression','Staff setup assistance','Exact deliverables listed before release'],delivery:'Release details will be posted when this package is finalized.',terms:['This package is not available for checkout yet.','Exact mechanics and deliverables will be defined before release.','All content remains subject to city balance, lore and roleplay standards.']}
];
export const coins=[
{slug:'10-coins',category:'MISFIT COINS',title:'10 Misfit Coins',price:'$12.50',image:'/images/coins/10.png',short:'10 Misfit Coins credited to your Project Misfits v2 account.',features:['10 Misfit Coins','Account delivery','Eligible PMv2 purchases'],delivery:'Account credit after transaction verification.',terms:['Coins may only be used for eligible Project Misfits v2 purchases.']},
{slug:'25-coins',category:'MISFIT COINS',title:'25 Misfit Coins',price:'$30',image:'/images/coins/25.png',short:'25 Misfit Coins credited to your Project Misfits v2 account.',features:['25 Misfit Coins','Account delivery','Eligible PMv2 purchases'],delivery:'Account credit after transaction verification.',terms:['Coins may only be used for eligible Project Misfits v2 purchases.']},
{slug:'50-coins',category:'MISFIT COINS',title:'50 Misfit Coins',price:'$60',image:'/images/coins/50.png',short:'50 Misfit Coins credited to your Project Misfits v2 account.',features:['50 Misfit Coins','Account delivery','Eligible PMv2 purchases'],delivery:'Account credit after transaction verification.',terms:['Coins may only be used for eligible Project Misfits v2 purchases.']},
{slug:'100-coins',category:'MISFIT COINS',title:'100 Misfit Coins',price:'$125',image:'/images/coins/100.png',short:'100 Misfit Coins credited to your Project Misfits v2 account.',features:['100 Misfit Coins','Account delivery','Eligible PMv2 purchases'],delivery:'Account credit after transaction verification.',terms:['Coins may only be used for eligible Project Misfits v2 purchases.']},
{slug:'250-coins',category:'MISFIT COINS',title:'250 Misfit Coins',price:'$280',image:'/images/coins/250.png',short:'250 Misfit Coins credited to your Project Misfits v2 account.',features:['250 Misfit Coins','Account delivery','Eligible PMv2 purchases'],delivery:'Account credit after transaction verification.',terms:['Coins may only be used for eligible Project Misfits v2 purchases.']},
{slug:'500-coins',category:'MISFIT COINS',title:'500 Misfit Coins',price:'$550',image:'/images/coins/500.png',short:'500 Misfit Coins credited to your Project Misfits v2 account.',features:['500 Misfit Coins','Account delivery','Eligible PMv2 purchases'],delivery:'Account credit after transaction verification.',terms:['Coins may only be used for eligible Project Misfits v2 purchases.']}
];
export const priorities=[
{slug:'bronze-priority',category:'PRIORITY',title:'Bronze Priority',price:'COMING SOON',image:'/images/priority/bronze.png',short:'Entry-level queue priority for Project Misfits v2.',features:['Bronze queue priority','Account-linked access','Subject to server priority rules'],delivery:'Activated after the final priority system launches.',terms:['Priority does not grant gameplay advantages or rule exemptions.']},
{slug:'silver-priority',category:'PRIORITY',title:'Silver Priority',price:'COMING SOON',image:'/images/priority/silver.png',short:'Upgraded queue priority for Project Misfits v2.',features:['Silver queue priority','Account-linked access','Subject to server priority rules'],delivery:'Activated after the final priority system launches.',terms:['Priority does not grant gameplay advantages or rule exemptions.']},
{slug:'gold-priority',category:'PRIORITY',title:'Gold Priority',price:'COMING SOON',image:'/images/priority/gold.png',short:'Premium queue priority for Project Misfits v2.',features:['Gold queue priority','Account-linked access','Subject to server priority rules'],delivery:'Activated after the final priority system launches.',terms:['Priority does not grant gameplay advantages or rule exemptions.']}
];
export const allStoreItems=[...products,...coins,...priorities];
export const getProduct=s=>allStoreItems.find(p=>p.slug===s);